# grid.R -- integer-composition enumeration of the discretized probability
# simplex (D.5). simplex_grid() is exported: its enumeration order DEFINES the
# tie-breaking rule of all grid searches in the package.

#' Enumerate the discretized probability simplex
#'
#' Enumerates all points of the probability simplex
#' \eqn{\{\lambda \in [0,1]^M : \sum_m \lambda_m = 1\}} on a regular grid with
#' increment `step`, using **integer arithmetic**: with \eqn{S = 1/\code{step}}
#' steps, every integer composition \eqn{(c_1, \dots, c_M)} with
#' \eqn{\sum_m c_m = S} and \eqn{c_m \ge 0} is listed and returned as
#' \eqn{c / S}. This is the grid over which [psave()] searches for the
#' propensity score mixing weights \eqn{\lambda} and the prognostic mixing
#' weights \eqn{\gamma}.
#'
#' @param M Integer; the number of mixture components (grid columns).
#' @param step Numeric; the grid increment. Must evenly divide 1 (checked in
#'   integer arithmetic: with `n_steps = round(1/step)`, the call errors unless
#'   `abs(n_steps * step - 1) < 1e-8`). Default `0.05`, the value used in
#'   Kabata, Stuart and Shintani (2024).
#'
#' @details
#' The number of grid points is exactly \eqn{\binom{S + M - 1}{M - 1}}; e.g.,
#' `M = 4`, `step = 0.05` gives `choose(23, 3) = 1771` points. Because the grid
#' is built from integer compositions, every valid point is present by
#' construction; the reference implementation of the paper instead filtered
#' `expand.grid()` rows with a floating-point `rowSums(gr) == 1` test, which
#' silently dropped about 10.6% of the valid points for `M = 4`,
#' `step = 0.05`.
#'
#' **Enumeration order (the tie-breaking rule).** Rows are generated by
#' recursive descent: \eqn{c_1} runs from \eqn{S} down to 0; within each value
#' of \eqn{c_1}, \eqn{c_2} runs from the remainder down to 0; and so on. The
#' first row is therefore \eqn{(1, 0, \dots, 0)} and the last row is
#' \eqn{(0, \dots, 0, 1)}. All grid searches in [psave()] resolve ties by
#' taking the **first** row attaining the minimum, within a 1e-9 relative
#' tolerance of the minimum, so ties favor learners listed earlier in
#' `ps.methods` / `prog.methods`. The tolerance is deliberate: criterion
#' values are computed with floating-point matrix algebra whose lowest-order
#' bits can differ across BLAS implementations, so an exact bitwise
#' `which.min()` would not be reproducible across machines, whereas the
#' tolerant first-minimum rule is.
#'
#' @return A numeric matrix with \eqn{\binom{S + M - 1}{M - 1}} rows and `M`
#'   columns; each row sums to 1 exactly (in integer arithmetic before the
#'   single final division by \eqn{S}).
#'
#' @references
#' Kabata D, Stuart EA, Shintani A (2024). Prognostic score-based model
#' averaging approach for propensity score estimation. *BMC Medical Research
#' Methodology*, 24, 228. \doi{10.1186/s12874-024-02350-y}
#'
#' @seealso [psave()], [psave_criteria()]
#' @examples
#' simplex_grid(2, step = 0.25)
#' nrow(simplex_grid(4, step = 0.05))  # choose(23, 3) = 1771
#'
#' # first row = all weight on the first component; last = on the last:
#' head(simplex_grid(3, step = 0.25), 3)
#' tail(simplex_grid(3, step = 0.25), 3)
#' @export
simplex_grid <- function(M, step = 0.05) {
  if (length(M) != 1L || is.na(M) || !is.numeric(M) || M < 1 ||
      abs(M - round(M)) > 1e-8) {
    stop("`M` must be a single positive integer.", call. = FALSE)
  }
  M <- as.integer(round(M))
  if (!is.numeric(step) || length(step) != 1L || is.na(step) ||
      step <= 0 || step > 1) {
    stop("`step` must be a single number in (0, 1].", call. = FALSE)
  }
  n_steps <- round(1 / step)
  if (abs(n_steps * step - 1) >= 1e-8) {
    stop("`step` must evenly divide 1 (e.g., 0.05, 0.1, 0.2, 0.25).",
         call. = FALSE)
  }
  .compositions(as.integer(n_steps), M) / n_steps
}

# All integer compositions of `total` into `parts` non-negative parts, in the
# documented descending enumeration order (first part from `total` down to 0,
# then recursively on the remainder).
.compositions <- function(total, parts) {
  if (parts == 1L) {
    return(matrix(total, nrow = 1L, ncol = 1L))
  }
  blocks <- vector("list", total + 1L)
  for (k in seq.int(total, 0L)) {
    sub <- .compositions(total - k, parts - 1L)
    blocks[[total - k + 1L]] <- cbind(matrix(k, nrow = nrow(sub), ncol = 1L), sub)
  }
  do.call(rbind, blocks)
}
